import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>hello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      <nav>
        <Link href='/' legacyBehavior><a>Home</a></Link>
        <Link href='/events' legacyBehavior><a>Events</a></Link>
        <Link href='/about-us' legacyBehavior><a>About Us</a></Link>
      </nav>
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`} legacyBehavior>
          <a>
            <Image width={100} height={100} src={ev.image}/>
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a>
          </Link>
        ))}
      </main>
      <footer>
      <p>created @2023</p>
      </footer>
    </>
  )
}

export async function getServerSideProps() {
  const {events_categories} = await import('/data/data.json');
  // console.log(events_categories);
  return {
    props:{
      data: events_categories
    },
  };
}
